export const DEFAULT_IGNORE_DIRS = new Set([
  'node_modules',
  'bower_components',
  '.git',
  '.svn',
  '.hg',
  '.idea',
  '.vscode',
  '.vs',
  '.cursor',
  '.windsurf',
  'dist',
  'build',
  'out',
  'target',
  'coverage',
  '.nyc_output',
  '__pycache__',
  '.pytest_cache',
  '.tox',
  'venv',
  '.venv',
  'env',
  '.env',
  'vendor',
  'tmp',
  'temp',
  '.cache',
  '.parcel-cache',
  '.next',
  '.nuxt',
  '.output',
  '.vercel',
  '.netlify',
  'Pods',
  'Carthage',
  '.build',
  'DerivedData',
  '.swiftpm',
  'xcuserdata',
  'Packages',
  'bin',
  'obj',
  'Debug',
  'Release',
  'x64',
  'x86',
  '.vs',
  'TestResults',
  'packages',
  '.gradle',
  '.m2',
  '.mvn',
  'gradle',
  'cmake-build-debug',
  'cmake-build-release',
  'CMakeFiles',
  '.dart_tool',
  '.flutter-plugins',
  '.flutter-plugins-dependencies',
  '.pub-cache',
  '.pub',
  'android/.gradle',
  'ios/Pods',
  'Godeps',
  '_obj',
  '_test',
  'pkg',
  'deps',
  '_build',
  'ebin',
  'priv/static',
  '.elixir_ls',
  '.mix',
  '.hex',
  '.rebar3',
  '_opam',
  '_esy',
  'esy.lock',
  '.stack-work',
  '.cabal-sandbox',
  'dist-newstyle',
  '.terraform',
  '.vagrant',
  'venv',
  'virtualenv',
  '.pytest_cache',
  '.mypy_cache',
  '.ruff_cache',
  '__pypackages__',
  'site-packages',
  '.bundle',
  'log',
  'logs',
  'tmp',
  '.sass-cache',
  '.jekyll-cache',
  '_site',
  '.docusaurus',
  '.astro',
  'public',
  '.turbo',
  '.contentlayer',
]);

export const DEFAULT_IGNORE_PATTERNS = [
  /\.min\.js$/,
  /\.bundle\.js$/,
  /\.map$/,
  /\.lock$/,
  /package-lock\.json$/,
  /yarn\.lock$/,
  /pnpm-lock\.yaml$/,
  /Podfile\.lock$/,
  /Gemfile\.lock$/,
  /Cargo\.lock$/,
  /composer\.lock$/,
  /poetry\.lock$/,
  /Pipfile\.lock$/,
  /go\.sum$/,
  /\.log$/,
  /\.pid$/,
  /\.seed$/,
  /\.pid\.lock$/,
  /\.gitignore$/,
  /\.gitattributes$/,
  /\.gitmodules$/,
  /\.npmignore$/,
  /\.dockerignore$/,
  /\.eslintignore$/,
  /\.prettierignore$/,
  /\.cursorignore$/,
  /\.cursorrules$/,
  /\.editorconfig$/,
  /\.xcworkspace$/,
  /\.xcodeproj$/,
  /\.pbxproj$/,
  /\.storyboard$/,
  /\.xib$/,
  /\.nib$/,
  /\.swiftmodule$/,
  /\.swiftdoc$/,
  /\.dSYM$/,
  /\.generated\.swift$/,
  /\.pb\.go$/,
  /\.pb\.h$/,
  /\.pb\.cc$/,
  /_pb2\.py$/,
  /\.g\.dart$/,
  /\.freezed\.dart$/,
  /\.gr\.dart$/,
  /\.config\.dart$/,
  /\.g\.cs$/,
  /\.designer\.cs$/,
  /AssemblyInfo\.cs$/,
  /\.meta$/,
  /\.prefab$/,
  /\.asset$/,
  /\.unity$/,
  /\.unitypackage$/,
];

export const BINARY_EXTENSIONS = new Set([
  'exe', 'dll', 'so', 'dylib', 'bin', 'app', 'dmg', 'pkg',
  'jpg', 'jpeg', 'png', 'gif', 'bmp', 'ico', 'svg', 'webp', 'tiff', 'psd', 'ai',
  'mp3', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'wav', 'ogg', 'webm', 'm4a', 'aac',
  'zip', 'tar', 'gz', 'rar', '7z', 'bz2', 'xz', 'tgz', 'tbz2',
  'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'odt', 'ods', 'odp',
  'ttf', 'otf', 'woff', 'woff2', 'eot',
  'class', 'jar', 'war', 'ear', 'aar', 'apk', 'ipa',
  'pyc', 'pyo', 'pyd', 'whl',
  'o', 'a', 'lib', 'obj', 'pdb', 'ilk', 'exp', 'idb',
  'dex', 'odex', 'vdex',
  'beam', 'boot',
  'rlib', 'rmeta',
  'wasm',
  'node',
  'vsix',
  'nupkg',
  'gem',
  'db', 'sqlite', 'sqlite3', 'mdb',
  'dat', 'data', 'sav', 'bak',
  'DS_Store',
  'Thumbs.db',
]);
